### ISSUE TITLE
XGBoost Error with Racing Method: There were no valid metrics for the ANOVA model.

### ISSUE THREAD

**Issue by simonschoe** [tidymodels/finetune#27]
Reproducible Example:
```r
library(palmerpenguins)

split <- penguins %>% 
  initial_split()

folds <- split %>% 
  training() %>% 
  vfold_cv(v=5)

rec_xgb <- 
  recipe(bill_depth_mm ~ ., data = penguins) %>% 
  step_unknown(all_nominal_predictors(), new_level = "missing")

spec_xgb <- 
  boost_tree(mode = "regression", engine = "xgboost") %>%
  set_args(
    trees = tune(),
    min_n = tune()
  )

grid_xgb <- 
  grid_regular(
    trees() %>% range_set(c(1, 200)),
    min_n(),
    levels = 3
  )

tune_race_anova(
    workflow(rec_xgb, spec_xgb),
    folds,
    grid = grid_xgb,
    metrics = metric_set(rmse),
    control = control_race(
      verbose = T, verbose_elim = T,
      burn_in = 2,
      alpha = 0.05,
      randomize = T
    )
  )
```
```r
Warning: All models failed. See the `.notes` column.
i Racing will minimize the mae metric.
i Resamples are analyzed in a random order.
Error: There were no valid metrics for the ANOVA model.
Run `rlang::last_error()` to see where the error occurred.
```
With my actual dataset I do not run into the error when using random forest or support vector regression, for example. It only occurs when trying to tune an XGB model.

@topepo Any ideas on where this error may come from? 🤔

**Comment by juliasilge** [comment]
Can you create a [reprex](https://reprex.tidyverse.org/) (a running minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it. I see you shared code here, but when I run it, I do not see the errors that you mention.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌

**Comment by simonschoe** [comment]
I figured it out by now, and am kind of embarrassed. The issue was that I didn't convert factor variables to dummies using `step_dummy` (I edited the example above and switched from `mtcars` to `penguins` to produce the shown behavior correctly). Even though this was explcitely stated in the `parnsip` XGB documentation, I falsely assumed that one-hot encoding would be performed automatically.

Since I also used parallel processing, I was only exposed to the error message above which made it hard to for me to debug the issue at first (more verbose error messages remained on the different cores and were not send back to the main session).

I will close this issue now. Sorry, for the mess... 😄
