### ISSUE TITLE
logged...

### ISSUE THREAD

**Issue by Steviey** [tidymodels/finetune#29]
Error in if (sum(filters_results$pass) == 2) { : 
  missing value where TRUE/FALSE needed

**Comment by juliasilge** [comment]
Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it.

If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You may already have reprex installed (it comes with the tidyverse package), but if not you can install it with:

```r
install.packages("reprex")
```

Thanks! 🙌
